export const marketingSubscriptionPlanGroups = [
  {
    title: '3M Care Packs',
    dealLabel: '2-month price',
    summary: 'Pay for 2 grooming services and receive credit value for 3 services, valid for 90 days.',
    plans: [
      {
        title: 'Monthly Care 3M',
        badge: 'Pay 2, Get 3',
        duration: '90 days',
        price: '₹1,798',
        worth: '₹2,697',
        sessions: '3 Monthly Care services',
        description: '3 Monthly Care grooming services at the price of 2.',
        serviceType: 'Grooming credit value',
      },
      {
        title: 'Fur Bath Care 3M',
        badge: 'Pay 2, Get 3',
        duration: '90 days',
        price: '₹2,798',
        worth: '₹4,197',
        sessions: '3 Fur Bath Care services',
        description: '3 Fur Bath Care services at the price of 2.',
        serviceType: 'Grooming credit value',
      },
      {
        title: 'Fur Makeover 3M',
        badge: 'Pay 2, Get 3',
        duration: '90 days',
        price: '₹2,998',
        worth: '₹4,497',
        sessions: '3 Fur Makeover services',
        description: '3 Fur Makeover services at the price of 2.',
        serviceType: 'Grooming credit value',
      },
      {
        title: 'Essential Care 3M',
        badge: 'Pay 2, Get 3',
        duration: '90 days',
        price: '₹3,598',
        worth: '₹5,397',
        sessions: '3 Essential Care services',
        description: '3 Essential Care grooming services at the price of 2.',
        serviceType: 'Grooming credit value',
        highlight: true,
      },
      {
        title: 'Complete Care 3M',
        badge: 'Full Care',
        duration: '90 days',
        price: '₹4,598',
        worth: '₹6,897',
        sessions: '3 Complete Care services',
        description: '3 Complete Care grooming services at the price of 2.',
        serviceType: 'Grooming credit value',
      },
    ],
  },
  {
    title: '6M Care Packs',
    dealLabel: '5-month price',
    summary: 'Pay for 5 grooming services and receive credit value for 6 services, valid for 180 days, with a final-service herbal shampoo bonus.',
    plans: [
      {
        title: 'Monthly Care 6M',
        badge: 'Shampoo Bonus',
        duration: '180 days',
        price: '₹4,495',
        worth: '₹5,394',
        sessions: '6 Monthly Care services',
        description: '6 Monthly Care grooming services at the price of 5.',
        serviceType: 'Grooming credit value',
        bonus: '+1 Herbal Shampoo Treatment on final service',
      },
      {
        title: 'Fur Bath Care 6M',
        badge: 'Shampoo Bonus',
        duration: '180 days',
        price: '₹6,995',
        worth: '₹8,394',
        sessions: '6 Fur Bath Care services',
        description: '6 Fur Bath Care services at the price of 5.',
        serviceType: 'Grooming credit value',
        bonus: '+1 Herbal Shampoo Treatment on final service',
      },
      {
        title: 'Fur Makeover 6M',
        badge: 'Shampoo Bonus',
        duration: '180 days',
        price: '₹7,495',
        worth: '₹8,994',
        sessions: '6 Fur Makeover services',
        description: '6 Fur Makeover services at the price of 5.',
        serviceType: 'Grooming credit value',
        bonus: '+1 Herbal Shampoo Treatment on final service',
      },
      {
        title: 'Essential Care 6M',
        badge: 'Popular 6M',
        duration: '180 days',
        price: '₹8,995',
        worth: '₹10,794',
        sessions: '6 Essential Care services',
        description: '6 Essential Care grooming services at the price of 5.',
        serviceType: 'Grooming credit value',
        bonus: '+1 Herbal Shampoo Treatment on final service',
      },
      {
        title: 'Complete Care 6M',
        badge: 'Best Value',
        duration: '180 days',
        price: '₹11,495',
        worth: '₹13,794',
        sessions: '6 Complete Care services',
        description: '6 Complete Care grooming services at the price of 5.',
        serviceType: 'Grooming credit value',
        bonus: '+1 Herbal Shampoo Treatment on final service',
        highlight: true,
      },
    ],
  },
] as const;

export type MarketingSubscriptionPlanGroup = (typeof marketingSubscriptionPlanGroups)[number];
export type MarketingSubscriptionPlan = MarketingSubscriptionPlanGroup['plans'][number];