export const dofursColors = {
  coral: '#e39a5d',
  coralDeep: '#c7783e',
  coralSoft: '#f7e3d2',
  ink: '#1f1f1f',
  inkSoft: '#4f4b47',
  surfaceWarm: '#fdf8f4',
  surfaceSoft: '#fff8f0',
  surfaceMuted: '#f6efe9',
  surfaceNeutral: '#f8f5f2',
  surfaceElevated: '#fffdf9',
  borderWarm: '#e7c4a7',
  borderSoft: '#edd7c6',
  accentSun: '#ffd8b0',
  accentMint: '#d8efe6',
  accentSky: '#dcecff',
  dangerSoft: '#fff2ef',
  success: '#22c55e',
  warning: '#f59e0b',
  error: '#ef4444',
  info: '#3b82f6',
  white: '#ffffff',
} as const;
