-- ============================================================
-- Migration 068: Refer & Earn
-- Tables: referral_codes, referral_redemptions,
--         user_credit_balance, credit_wallet_transactions
-- Adds: bookings.wallet_credits_applied_inr
-- ============================================================

-- ------------------------------------------------------------
-- TABLE: referral_codes
-- One row per user; unique code auto-generated by trigger.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS referral_codes (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  code            text        NOT NULL UNIQUE,
  total_referrals int         NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_referral_codes_code    ON referral_codes(code);
CREATE INDEX IF NOT EXISTS idx_referral_codes_user_id ON referral_codes(user_id);

-- ------------------------------------------------------------
-- TABLE: referral_redemptions
-- One row per successful referral sign-up event.
-- UNIQUE on referee_user_id so each user can only be a referee once.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS referral_redemptions (
  id                   uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  referral_code        text        NOT NULL,
  referrer_user_id     uuid        NOT NULL REFERENCES users(id),
  referee_user_id      uuid        NOT NULL REFERENCES users(id),
  status               text        NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'credited', 'failed')),
  referrer_credited_at timestamptz,
  referee_credited_at  timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (referee_user_id)
);

CREATE INDEX IF NOT EXISTS idx_referral_redemptions_referrer ON referral_redemptions(referrer_user_id);
CREATE INDEX IF NOT EXISTS idx_referral_redemptions_referee  ON referral_redemptions(referee_user_id);
CREATE INDEX IF NOT EXISTS idx_referral_redemptions_code     ON referral_redemptions(referral_code);

-- ------------------------------------------------------------
-- TABLE: user_credit_balance
-- Monetary credit wallet per user (whole rupees).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_credit_balance (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             uuid        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  available_inr       int         NOT NULL DEFAULT 0 CHECK (available_inr >= 0),
  lifetime_earned_inr int         NOT NULL DEFAULT 0,
  lifetime_used_inr   int         NOT NULL DEFAULT 0,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_credit_balance_user_id ON user_credit_balance(user_id);

-- ------------------------------------------------------------
-- TABLE: credit_wallet_transactions
-- Immutable audit log of every credit change.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS credit_wallet_transactions (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount_inr       int         NOT NULL,
  transaction_type text        NOT NULL
                     CHECK (transaction_type IN (
                       'referral_reward_referrer',
                       'referral_reward_referee',
                       'booking_applied',
                       'booking_refunded',
                       'admin_grant',
                       'admin_deduct',
                       'expired'
                     )),
  reference_id     uuid,
  notes            text,
  balance_after    int         NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cwt_user_id ON credit_wallet_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_cwt_type    ON credit_wallet_transactions(transaction_type);

-- ------------------------------------------------------------
-- COLUMN: bookings.wallet_credits_applied_inr
-- Tracks how much credit wallet was used for this booking.
-- ------------------------------------------------------------
ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS wallet_credits_applied_inr int NOT NULL DEFAULT 0;

-- ------------------------------------------------------------
-- FUNCTION: generate_referral_code()
-- Generates DOF + 6 chars avoiding visually confusable chars.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION generate_referral_code()
RETURNS text AS $$
DECLARE
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code  text := 'DOF';
  i     int;
BEGIN
  FOR i IN 1..6 LOOP
    code := code || substr(chars, floor(random() * length(chars) + 1)::int, 1);
  END LOOP;
  RETURN code;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- FUNCTION + TRIGGER: auto-create referral code on user insert
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_fn_create_referral_code()
RETURNS trigger AS $$
DECLARE
  new_code text;
  attempts int := 0;
BEGIN
  LOOP
    new_code := generate_referral_code();
    EXIT WHEN NOT EXISTS (SELECT 1 FROM referral_codes WHERE code = new_code);
    attempts := attempts + 1;
    IF attempts > 20 THEN
      RAISE EXCEPTION 'Could not generate unique referral code after 20 attempts';
    END IF;
  END LOOP;

  INSERT INTO referral_codes (user_id, code)
  VALUES (NEW.id, new_code)
  ON CONFLICT (user_id) DO NOTHING;

  INSERT INTO user_credit_balance (user_id)
  VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_create_referral_code ON users;
CREATE TRIGGER trg_create_referral_code
  AFTER INSERT ON users
  FOR EACH ROW EXECUTE FUNCTION trg_fn_create_referral_code();

-- ------------------------------------------------------------
-- BACKFILL: generate codes + balance rows for existing users
-- ------------------------------------------------------------
DO $$
DECLARE
  usr      RECORD;
  new_code text;
  chars    text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  i        int;
  attempts int;
BEGIN
  FOR usr IN
    SELECT id FROM users
    WHERE id NOT IN (SELECT user_id FROM referral_codes)
  LOOP
    attempts := 0;
    LOOP
      new_code := 'DOF';
      FOR i IN 1..6 LOOP
        new_code := new_code || substr(chars, floor(random() * length(chars) + 1)::int, 1);
      END LOOP;
      EXIT WHEN NOT EXISTS (SELECT 1 FROM referral_codes WHERE code = new_code);
      attempts := attempts + 1;
      IF attempts > 20 THEN
        RAISE EXCEPTION 'Backfill: too many retries for user %', usr.id;
      END IF;
    END LOOP;
    INSERT INTO referral_codes (user_id, code) VALUES (usr.id, new_code)
    ON CONFLICT DO NOTHING;
  END LOOP;

  INSERT INTO user_credit_balance (user_id)
  SELECT id FROM users
  WHERE id NOT IN (SELECT user_id FROM user_credit_balance)
  ON CONFLICT DO NOTHING;
END;
$$;

-- ------------------------------------------------------------
-- RLS POLICIES
-- ------------------------------------------------------------

ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;

-- Any authenticated user can read any code (needed for validation at sign-up)
CREATE POLICY "referral_codes_select_any"
  ON referral_codes FOR SELECT
  USING (true);

CREATE POLICY "referral_codes_service_role_all"
  ON referral_codes FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

-- ---
ALTER TABLE referral_redemptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "referral_redemptions_select_own"
  ON referral_redemptions FOR SELECT
  USING (auth.uid() = referrer_user_id OR auth.uid() = referee_user_id);

CREATE POLICY "referral_redemptions_service_role_all"
  ON referral_redemptions FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

-- ---
ALTER TABLE user_credit_balance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user_credit_balance_select_own"
  ON user_credit_balance FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "user_credit_balance_service_role_all"
  ON user_credit_balance FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

-- ---
ALTER TABLE credit_wallet_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "credit_wallet_transactions_select_own"
  ON credit_wallet_transactions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "credit_wallet_transactions_service_role_all"
  ON credit_wallet_transactions FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);
