export const BUSINESS_REFERRAL_CAMPAIGN_KEY = 'welcome_offer';
export const DEFAULT_BUSINESS_REFERRAL_CODE = 'PETFIRST250';
export const DEFAULT_BUSINESS_REFEREE_REWARD_INR = 250;
export const DEFAULT_BUSINESS_REFERRER_REWARD_INR = 250;
export const REFERRAL_CODE_MAX_LENGTH = 32;
export const REFERRAL_CODE_INPUT_PATTERN = /^[A-Za-z0-9]+$/;
